package greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.bean.Weight;
import greendao.bean.Themes;

import greendao.dao.WeightDao;
import greendao.dao.ThemesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weightDaoConfig;
    private final DaoConfig themesDaoConfig;

    private final WeightDao weightDao;
    private final ThemesDao themesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weightDaoConfig = daoConfigMap.get(WeightDao.class).clone();
        weightDaoConfig.initIdentityScope(type);

        themesDaoConfig = daoConfigMap.get(ThemesDao.class).clone();
        themesDaoConfig.initIdentityScope(type);

        weightDao = new WeightDao(weightDaoConfig, this);
        themesDao = new ThemesDao(themesDaoConfig, this);

        registerDao(Weight.class, weightDao);
        registerDao(Themes.class, themesDao);
    }
    
    public void clear() {
        weightDaoConfig.getIdentityScope().clear();
        themesDaoConfig.getIdentityScope().clear();
    }

    public WeightDao getWeightDao() {
        return weightDao;
    }

    public ThemesDao getThemesDao() {
        return themesDao;
    }

}
