package greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.bean.Themes;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "THEMES".
*/
public class ThemesDao extends AbstractDao<Themes, Long> {

    public static final String TABLENAME = "THEMES";

    /**
     * Properties of entity Themes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Select = new Property(1, Boolean.class, "select", false, "SELECT");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Theme_id = new Property(3, Integer.class, "theme_id", false, "THEME_ID");
        public final static Property Base_color = new Property(4, Integer.class, "base_color", false, "BASE_COLOR");
    };


    public ThemesDao(DaoConfig config) {
        super(config);
    }
    
    public ThemesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"THEMES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SELECT\" INTEGER," + // 1: select
                "\"NAME\" TEXT," + // 2: name
                "\"THEME_ID\" INTEGER," + // 3: theme_id
                "\"BASE_COLOR\" INTEGER);"); // 4: base_color
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"THEMES\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Themes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean select = entity.getSelect();
        if (select != null) {
            stmt.bindLong(2, select ? 1L: 0L);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Integer theme_id = entity.getTheme_id();
        if (theme_id != null) {
            stmt.bindLong(4, theme_id);
        }
 
        Integer base_color = entity.getBase_color();
        if (base_color != null) {
            stmt.bindLong(5, base_color);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Themes readEntity(Cursor cursor, int offset) {
        Themes entity = new Themes( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0, // select
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // theme_id
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4) // base_color
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Themes entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSelect(cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0);
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTheme_id(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setBase_color(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Themes entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Themes entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
