package greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "THEMES".
 */
public class Themes {

    private Long id;
    private Boolean select;
    private String name;
    private Integer theme_id;
    private Integer base_color;

    public Themes() {
    }

    public Themes(Long id) {
        this.id = id;
    }

    public Themes(Long id, Boolean select, String name, Integer theme_id, Integer base_color) {
        this.id = id;
        this.select = select;
        this.name = name;
        this.theme_id = theme_id;
        this.base_color = base_color;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getSelect() {
        return select;
    }

    public void setSelect(Boolean select) {
        this.select = select;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getTheme_id() {
        return theme_id;
    }

    public void setTheme_id(Integer theme_id) {
        this.theme_id = theme_id;
    }

    public Integer getBase_color() {
        return base_color;
    }

    public void setBase_color(Integer base_color) {
        this.base_color = base_color;
    }

}
